# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CY8IVJOVXUDc2qB2y8I81xNENk6M-MLI
"""

!pip install google-play-scraper

from google_play_scraper import app

import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np
seed = 0
np.random.seed(seed)
import matplotlib.pyplot as plt
import seaborn as sns

import datetime as dt
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

!pip install sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

from wordcloud import WordCloud

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

from google_play_scraper import app, reviews, Sort

scrapreview = reviews(
    'com.telkomsel.telkomselcm',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=10500
)

print(type(scrapreview))
print(type(scrapreview[0]))
print(scrapreview[0])

import csv

with open('Dataset hasil scraping.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review'])
    list_of_reviews, continuation_token = scrapreview
    for review in list_of_reviews:
        writer.writerow([review['content']])

